spring:
  application:
    name: reward-service
    description:
  datasource:
    database: reward_service_db
    hostname: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    username: ${POSTGRES_USER:khoffy}
    password: ${POSTGRES_PASSWD:SwaY890}
    url: jdbc:postgresql://${spring.datasource.hostname}:${spring.datasource.port}/${spring.datasource.database}
  initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
#  data:
#    mongodb:
#      uri: "mongodb://localhost:27017"
#      database: reward-service-db
#      host: localhost
#      port: 27017
server:
  port: 8097
