spring:
  application:
    name: user-service
    description:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fotodummy2@gmail.com
    password: vfpmfcpplwmxepya
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: false

  data:
    mongodb:
      uri: "mongodb://localhost:27017"
      database: avatar-service-db
      host: localhost
      port: 27017
server:
  port: 8089

